## This hook helps to setup the root folder to store redis-ha data
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "redis-ha.fullname" . }}-init-volume
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  selector:
    matchLabels:
      heritage: {{.Release.Service | quote }}
      release: {{.Release.Name | quote }}
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  template:
    metadata:
      name: {{ template "redis-ha.fullname" . }}-init-volume
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: pre-install-job
        image: "alpine:3.3"
        volumeMounts:
          - mountPath: /redis-data-root
            name: data
        command: 
        - /bin/bash
        - -c
        - "/bin/mkdir -p /redis-data-root{{ template "redis-ha.fullMountHostPath" . }} && sleep infinity"
      volumes:
      - name: data
{{- if .Values.persistence.enabled }}
        hostPath: 
          path: "/"
          type: Directory
{{- end }}
        